version: '3'

services:
  seo_agent:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./reports:/app/reports
    environment:
      - SEMRUSH_API_KEY=${SEMRUSH_API_KEY}
      - AHREFS_API_KEY=${AHREFS_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERP_API_KEY=${SERP_API_KEY}
      - DOMAIN=${DOMAIN:-asendia.ai}
      - COMPETITORS=${COMPETITORS}
    restart: unless-stopped
    
  scheduler:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./reports:/app/reports
    environment:
      - SEMRUSH_API_KEY=${SEMRUSH_API_KEY}
      - AHREFS_API_KEY=${AHREFS_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERP_API_KEY=${SERP_API_KEY}
      - DOMAIN=${DOMAIN:-asendia.ai}
      - COMPETITORS=${COMPETITORS}
    command: ["python", "schedule_weekly.py"]
    restart: unless-stopped